const products = [
  { id: '1', category:'notebooks', name: 'Notebook Celeron 14" Memoria 4gb Almacenaje 128gb - Tedge', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', price: '49.399', photo: 'https://http2.mlstatic.com/D_NQ_NP_908610-MLA45342957241_032021-V.webp', stock: '10' },
  { id: '2', category:'notebooks', name: 'Notebook Lenovo IdeaPad 14IIL05 platinum gray 14", Intel Core i5 1035G1 8GB de RAM 512GB SSD, Gráficos Intel UHD G1 1920x1080px', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', price: '102.599', photo: 'https://http2.mlstatic.com/D_NQ_NP_879170-MLA45629747467_042021-V.webp', stock: '4' },
  { id: '3', category:'printers', name: 'Impresora simple función Xerox Phaser 3020/BI con wifi blanca y azul 220V - 240V', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', price: '14.999', photo: 'https://http2.mlstatic.com/D_NQ_NP_933053-MLA41241337999_032020-V.webp', stock: '6' },
  { id: '4', category:'tablets', name: 'Tablet Samsung Galaxy Tab A7 SM-T500 10.4" 64GB dark gray con 3GB de memoria RAM', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', price: '37.999', photo: 'https://http2.mlstatic.com/D_NQ_NP_992019-MLA44207852270_112020-V.webp', stock: '8' },
  { id: '5', category:'computers', name: 'Pc Armada Slim Intel Amd Dual Core Hd 1tb 8gb Ram Lol Hdmi', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', price: '49.999', photo: 'https://http2.mlstatic.com/D_NQ_NP_991401-MLA31351342525_072019-V.webp', stock: '22' },
]

export const getFetch = new Promise((resolve) => {
  setTimeout(() => {
    resolve(products)
  }, 2000);
})
